version: '3'
services:
  web:
    build:  .
    ports:
     - "3001:80"
    volumes:
     - /home/nik/DEV/tm.scansend.su/src:/var/www/html
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /home/nik/DEV/tm.scansend.su/DATA:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
