#! /bin/bash

#crontab -u <user> -e
#

#0 18 * * * command to be executed
#^ you need to set the minute, too. Else it would be running every minute on the 18th hour
#How to setup a cronjob in general:

 # * * * * *  command to execute
 # │ │ │ │ │
 # │ │ │ │ │
 # │ │ │ │ └───── day of week (0 - 6) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)
 # │ │ │ └────────── month (1 - 12)
 # │ │ └─────────────── day of month (1 - 31)
 # │ └──────────────────── hour (0 - 23)
 # └───────────────────────── min (0 - 59)

0 18 * * * <command to be executed> 